#!/bin/bash
set -e
NAME="$1"
TAG="$2"

# Place the tests inside the container
cat /puzzles/puzzles.tar | docker run -i -a stdin lonnen/buildstep /bin/bash -c "mkdir -p /runner && tar -xC /runner"

# Place the contestent's name inside the container
docker run -i -a stdin lonnen/buildstep /bin/bash -c "export PLAYER=$NAME"

# Place the app inside the tests directory
ID=$(cat | docker run -i -a stdin lonnen/buildstep /bin/bash -c "mkdir -p /app/solutions && tar -xC /app/solutions")
test $(docker wait $ID) -eq 0
docker commit $ID $NAME $TAG > /dev/null

# Run the builder script and attach to view output
if [[ -z "$TAG" ]]; then
  IMAGE=$NAME
else
  IMAGE=$NAME:$TAG
fi
ID=$(docker run -d $IMAGE /build/builder)
docker attach $ID
test $(docker wait $ID) -eq 0
docker commit $ID $NAME $TAG > /dev/null
