#!/bin/bash
set -e

app_root=/app
build_root=/build/app
cache_root=/cache/app

cp -r /app /build

mkdir -p $cache_root
mkdir -p $build_root/.profile.d

echo "-----> Getting to know your project ..."

cat > /exec <<EOF
#!/bin/bash
export HOME=/app
for file in $app_root/.profile.d/*; do source \$file; done
hash -r
cd $app_root
"\$@"
EOF
chmod +x /exec

cat > /start <<EOF
cd /app
./runtests puzzles/ solutions/
EOF
chmod +x /start

rm -fR /app
mv /build/app /
