#!/bin/bash
#
# Prepares the "stack" to run apps
#

#
# SYSTEM PACKAGES
#
apt-get update
xargs apt-get install -y --force-yes < /build/packages.txt
# node is a delicate snowflake
add-apt-repository -y ppa:chris-lea/node.js
apt-get update
apt-get -y dist-upgrade nodejs
ln -s /usr/bin/nodejs /usr/bin/node
apt-get clean
